name: Changelog check
o: [pull_request]

jobs:
  changelog_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for changelog files
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context);
